// Generated by scripts/sync-shop.mjs from the public Shopify catalogue at
// store.encompassspa.com (/collections/<handle>/products.json needs no API key).
// Do not edit by hand — re-run the script instead.
export const SHOP_URL = 'https://store.encompassspa.com'

export type ShopProduct = { handle: string; title: string; vendor: string; price: string | null; image: string | null }
export type ShopCollection = { handle: string; title: string; count: number; products: ShopProduct[] }

export const COLLECTIONS: Record<string, ShopCollection> = {
  "adrenal-support": {
    "handle": "adrenal-support",
    "title": "Adrenal Support",
    "count": 16,
    "products": [
      {
        "handle": "5-htp",
        "title": "5-HTP",
        "vendor": "Ortho Molecular",
        "price": "56.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/5-HTP.png?v=1631826763"
      },
      {
        "handle": "adren-all",
        "title": "Adren-all",
        "vendor": "Ortho Molecular",
        "price": "34.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Adren-All_8fae8949-4552-4d1b-b78f-40ce114bd294.png?v=1631828059"
      },
      {
        "handle": "adrenal-essence-60s",
        "title": "Adrenal Essence",
        "vendor": "Xymogen",
        "price": "38.95",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_4.png?v=1631829158"
      },
      {
        "handle": "adrenal-manager-60c",
        "title": "Adrenal Manager",
        "vendor": "Xymogen",
        "price": "23.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_5.png?v=1631829210"
      }
    ]
  },
  "blood-sugar-support": {
    "handle": "blood-sugar-support",
    "title": "Blood Sugar Support",
    "count": 6,
    "products": [
      {
        "handle": "alpha-lipoic-acid",
        "title": "Alpha Lipoic Acid",
        "vendor": "Ortho Molecular",
        "price": "53.60",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-505060-Alpha_Lipoic_Acid.png?v=1730742785"
      },
      {
        "handle": "caprylic-acid",
        "title": "Caprylic Acid",
        "vendor": "Pure Encapsulations",
        "price": "26.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_91.jpg?v=1633549370"
      },
      {
        "handle": "diaxinol",
        "title": "Diaxinol",
        "vendor": "Ortho Molecular",
        "price": "93.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_37.jpg?v=1632425410"
      },
      {
        "handle": "ultra-flora-control",
        "title": "Ultra Flora Control",
        "vendor": "Metagenics",
        "price": "44.95",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/ultraflora.png?v=1618873504"
      }
    ]
  },
  "cardiovascular-support": {
    "handle": "cardiovascular-support",
    "title": "Cardiovascular Support",
    "count": 15,
    "products": [
      {
        "handle": "bergamot-bpf-120s",
        "title": "Bergamot BPF 120'S",
        "vendor": "Ortho Molecular",
        "price": "89.50",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_88.jpg?v=1633548298"
      },
      {
        "handle": "cholestepure",
        "title": "CholestePure",
        "vendor": "Pure Encapsulations",
        "price": "51.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/1_6f1b8a3f-f0d8-4f2e-bedf-fe11327fa778.jpg?v=1678906969"
      },
      {
        "handle": "citranox",
        "title": "CitraNOX",
        "vendor": "Ortho Molecular",
        "price": "52.60",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/CitraNOX_cc2ffeed-7e10-43d7-9913-6c393c00af46.jpg?v=1632423220"
      },
      {
        "handle": "cm-core",
        "title": "CM Core",
        "vendor": "Ortho Molecular",
        "price": "52.60",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/cmcore.jpg?v=1618867954"
      }
    ]
  },
  "energy-support": {
    "handle": "energy-support",
    "title": "Energy Support",
    "count": 15,
    "products": [
      {
        "handle": "carnitex",
        "title": "CarniteX",
        "vendor": "Xymogen",
        "price": "35.77",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_28.jpg?v=1632419042"
      },
      {
        "handle": "cogniquil",
        "title": "Cogniquil",
        "vendor": "Xymogen",
        "price": "67.99",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_30.jpg?v=1632423579"
      },
      {
        "handle": "dhea-25mg",
        "title": "DHEA 25mg",
        "vendor": "Ortho Molecular",
        "price": "22.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_34.jpg?v=1632425099"
      },
      {
        "handle": "dhea-5mg",
        "title": "DHEA 5mg",
        "vendor": "Ortho Molecular",
        "price": "15.70",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_35.jpg?v=1632425167"
      }
    ]
  },
  "gastrointestinal-health": {
    "handle": "gastrointestinal-health",
    "title": "Gastrointestinal Health",
    "count": 55,
    "products": [
      {
        "handle": "arabinogalactan-90s",
        "title": "Arabinogalactan",
        "vendor": "Pure Encapsulations",
        "price": "47.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Arabinogalactan90.jpg?v=1618866884"
      },
      {
        "handle": "atrantil",
        "title": "Atrantil",
        "vendor": "Atrantil",
        "price": "39.95",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_9.png?v=1631831973"
      },
      {
        "handle": "betaine-pepsin",
        "title": "Betaine & Pepsin",
        "vendor": "Ortho Molecular",
        "price": "41.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-543225-Betaine_And_Pepsin.png?v=1730743077"
      },
      {
        "handle": "biocidin-caspsules",
        "title": "Biocidin Capsules",
        "vendor": "Bio Botanical Research",
        "price": "66.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/BiocidinCapsules.jpg?v=1631826019"
      }
    ]
  },
  "general-nutrition": {
    "handle": "general-nutrition",
    "title": "General Nutrition",
    "count": 35,
    "products": [
      {
        "handle": "buffered-c-caps",
        "title": "Buffered C Caps",
        "vendor": "Ortho Molecular",
        "price": "24.20",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/BufferedCCapsules.png?v=1634168163"
      },
      {
        "handle": "buffered-vitamin-c-powder",
        "title": "Buffered C Powder",
        "vendor": "Ortho Molecular",
        "price": "50.50",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-140300-Buffered_Vitamin_C.png?v=1730740211"
      },
      {
        "handle": "complete-mitochondrial-support",
        "title": "Complete Mitochondrial Support",
        "vendor": "Ortho Molecular",
        "price": "66.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/smartmockups_kl2vv94j.png?v=1620786451"
      },
      {
        "handle": "copper-60s",
        "title": "Copper 60s",
        "vendor": "Pure Encapsulations",
        "price": "11.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/copper.jpg?v=1618868017"
      }
    ]
  },
  "hormone-balance": {
    "handle": "hormone-balance",
    "title": "Hormone Balance",
    "count": 9,
    "products": [
      {
        "handle": "advanced-estrogen-detoxification",
        "title": "Advanced Estrogen Detoxification",
        "vendor": "Ortho Molecular",
        "price": "84.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-635060-Advanced_Estrogen_Detoxification.png?v=1730743763"
      },
      {
        "handle": "balance",
        "title": "Balance",
        "vendor": "Ortho Molecular",
        "price": "34.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/balanc.png?v=1618867052"
      },
      {
        "handle": "dhea-25mg",
        "title": "DHEA 25mg",
        "vendor": "Ortho Molecular",
        "price": "22.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_34.jpg?v=1632425099"
      },
      {
        "handle": "dhea-5mg",
        "title": "DHEA 5mg",
        "vendor": "Ortho Molecular",
        "price": "15.70",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_35.jpg?v=1632425167"
      }
    ]
  },
  "immune-support": {
    "handle": "immune-support",
    "title": "Immune Support",
    "count": 96,
    "products": [
      {
        "handle": "alpha-lipoic-acid",
        "title": "Alpha Lipoic Acid",
        "vendor": "Ortho Molecular",
        "price": "53.60",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-505060-Alpha_Lipoic_Acid.png?v=1730742785"
      },
      {
        "handle": "atrantil",
        "title": "Atrantil",
        "vendor": "Atrantil",
        "price": "39.95",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_9.png?v=1631831973"
      },
      {
        "handle": "biocidin-caspsules",
        "title": "Biocidin Capsules",
        "vendor": "Bio Botanical Research",
        "price": "66.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/BiocidinCapsules.jpg?v=1631826019"
      },
      {
        "handle": "biocidin-liquid",
        "title": "Biocidin Liquid",
        "vendor": "Bio Botanical Research",
        "price": "63.97",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/BiocidinLiquid_d3c500d2-85eb-4b70-ae64-d0d23902d6ff.jpg?v=1631826044"
      }
    ]
  },
  "joint-and-muscle-health": {
    "handle": "joint-and-muscle-health",
    "title": "Joint and Muscle Health",
    "count": 7,
    "products": [
      {
        "handle": "boswella-akba-60s",
        "title": "Boswellia AKBA 60S",
        "vendor": "Pure Encapsulations",
        "price": "34.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/boswellia.jpg?v=1618867433"
      },
      {
        "handle": "e-p-o-evening-primrose-oil",
        "title": "E.P.O. - Evening Primrose Oil",
        "vendor": "Pure Encapsulations",
        "price": "31.40",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/E.P.O..jpg?v=1637697537"
      },
      {
        "handle": "glucosamine-sulfate",
        "title": "Glucosamine Sulfate",
        "vendor": "Ortho Molecular",
        "price": "41.20",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/glucosamine.png?v=1618869113"
      },
      {
        "handle": "spm-active",
        "title": "SPM Active",
        "vendor": "Metagenics",
        "price": "73.50",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/SMPActive.jpg?v=1737402732"
      }
    ]
  },
  "liver-health-and-detoxification": {
    "handle": "liver-health-and-detoxification",
    "title": "Liver Health and Detoxification",
    "count": 32,
    "products": [
      {
        "handle": "alpha-lipoic-acid",
        "title": "Alpha Lipoic Acid",
        "vendor": "Ortho Molecular",
        "price": "53.60",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-505060-Alpha_Lipoic_Acid.png?v=1730742785"
      },
      {
        "handle": "buffered-c-caps",
        "title": "Buffered C Caps",
        "vendor": "Ortho Molecular",
        "price": "24.20",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/BufferedCCapsules.png?v=1634168163"
      },
      {
        "handle": "buffered-vitamin-c-powder",
        "title": "Buffered C Powder",
        "vendor": "Ortho Molecular",
        "price": "50.50",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/FIL405-140300-Buffered_Vitamin_C.png?v=1730740211"
      },
      {
        "handle": "carnitex",
        "title": "CarniteX",
        "vendor": "Xymogen",
        "price": "35.77",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_28.jpg?v=1632419042"
      }
    ]
  },
  "memory": {
    "handle": "memory",
    "title": "Memory & Mood Support",
    "count": 32,
    "products": [
      {
        "handle": "5-htp",
        "title": "5-HTP",
        "vendor": "Ortho Molecular",
        "price": "56.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/5-HTP.png?v=1631826763"
      },
      {
        "handle": "adren-all",
        "title": "Adren-all",
        "vendor": "Ortho Molecular",
        "price": "34.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Adren-All_8fae8949-4552-4d1b-b78f-40ce114bd294.png?v=1631828059"
      },
      {
        "handle": "adrenal-essence-60s",
        "title": "Adrenal Essence",
        "vendor": "Xymogen",
        "price": "38.95",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_4.png?v=1631829158"
      },
      {
        "handle": "adrenal-manager-60c",
        "title": "Adrenal Manager",
        "vendor": "Xymogen",
        "price": "23.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_5.png?v=1631829210"
      }
    ]
  },
  "sexual-health": {
    "handle": "sexual-health",
    "title": "Sexual Health",
    "count": 0,
    "products": []
  },
  "skin-care": {
    "handle": "skin-care",
    "title": "Skin Care",
    "count": 55,
    "products": [
      {
        "handle": "alpharet-clearing-serum",
        "title": "AlphaRet Clearing Serum",
        "vendor": "SkinBetter Science",
        "price": "144.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/AlphaRet_Clearing_Serum.webp?v=1733858417"
      },
      {
        "handle": "alpharet-exfoliating-facial-peel-pads",
        "title": "AlphaRet Exfoliating Facial Peel Pads",
        "vendor": "SkinBetter Science",
        "price": "123.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/AlphaRet-Exfoliating-Peel-Pads.webp?v=1733858908"
      },
      {
        "handle": "alpharet-overnight-cream",
        "title": "AlphaRet Overnight Cream",
        "vendor": "SkinBetter Science",
        "price": "144.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/AlphaRetOvernightCreamBottle.webp?v=1733859278"
      },
      {
        "handle": "alto-advanced-defense-and-repair-serum",
        "title": "Alto Advanced Defense and Repair Serum",
        "vendor": "SkinBetter Science",
        "price": "200.00",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/AltoAdvDefense_Repair.webp?v=1733859667"
      }
    ]
  },
  "weight-management": {
    "handle": "weight-management",
    "title": "Weight Management",
    "count": 15,
    "products": [
      {
        "handle": "caprylic-acid",
        "title": "Caprylic Acid",
        "vendor": "Pure Encapsulations",
        "price": "26.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_91.jpg?v=1633549370"
      },
      {
        "handle": "carnitex",
        "title": "CarniteX",
        "vendor": "Xymogen",
        "price": "35.77",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_28.jpg?v=1632419042"
      },
      {
        "handle": "crave-control",
        "title": "Crave Control",
        "vendor": "Ortho Molecular",
        "price": "46.90",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/files/CraveControlforShopify.png?v=1704222447"
      },
      {
        "handle": "diaxinol",
        "title": "Diaxinol",
        "vendor": "Ortho Molecular",
        "price": "93.80",
        "image": "https://cdn.shopify.com/s/files/1/0531/2865/9095/products/Untitleddesign_37.jpg?v=1632425410"
      }
    ]
  }
}

export function collectionUrl(handle: string) { return `${SHOP_URL}/collections/${handle}` }
export function productUrl(handle: string) { return `${SHOP_URL}/products/${handle}` }
