// GENERATED by scripts/sync-skincare-brands.mjs from the live Shopify catalogue
// at store.encompassspa.com/collections/skin-care. Do not edit by hand.
//
// 55 products across 4 brands at the time of generation.
import type { PriceMenu } from '@/components/templates/ServicePageTemplate'

export const SKINCARE_BRAND_COUNT = 4
export const SKINCARE_PRODUCT_COUNT = 55

export const SKINCARE_MENUS: PriceMenu[] = [
  {
    "heading": "SkinCeuticals",
    "items": [
      {
        "name": "Antioxidant Lip Repair",
        "price": "$42",
        "href": "https://store.encompassspa.com/products/antioxidant-lip-repair?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "AOX+ Eye Gel",
        "price": "$98",
        "href": "https://store.encompassspa.com/products/aox-eye-gel?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Blemish + Age Defense",
        "price": "$99",
        "href": "https://store.encompassspa.com/products/blemish-age-defense?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Body Retexturing Treatment",
        "price": "$66",
        "href": "https://store.encompassspa.com/products/body-retexturing-treatment?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "C E Ferulic",
        "price": "$173.50",
        "href": "https://store.encompassspa.com/products/c-e-ferulic?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Clarifying Clay Mask",
        "price": "$60",
        "href": "https://store.encompassspa.com/products/clarifying-clay-mask?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Daily Moisture",
        "price": "$66",
        "href": "https://store.encompassspa.com/products/daily-moisture?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Discoloration Defense",
        "price": "$102",
        "href": "https://store.encompassspa.com/products/discoloration-defense?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Epidermal Repair",
        "price": "$78",
        "href": "https://store.encompassspa.com/products/epidermal-repair?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Glycolic 10 Renew Overnight",
        "price": "$84",
        "href": "https://store.encompassspa.com/products/glycolic-10-renew-on?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Glycolic Renewal Cleanser",
        "price": "$42",
        "href": "https://store.encompassspa.com/products/glycolic-renewal-cleanser?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "HA Intensifier",
        "price": "$106",
        "href": "https://store.encompassspa.com/products/ha-intensifier?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Hydrating B5 Gel",
        "price": "$86",
        "href": "https://store.encompassspa.com/products/hydrating-b5-gel?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "LHA Toner",
        "price": "$44",
        "href": "https://store.encompassspa.com/products/lha-toner?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Micro-Exfoliating Scrub",
        "price": "$35",
        "href": "https://store.encompassspa.com/products/micro-exfoliating-scrub?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Phloretin CF",
        "price": "$169",
        "href": "https://store.encompassspa.com/products/phloretin-cf?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Physical Fusion UV Defense SPF 50",
        "price": "$35",
        "href": "https://store.encompassspa.com/products/physical-fusion-uv-defense-spf-50?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Phyto A+ Brightening Treatment",
        "price": "$110",
        "href": "https://store.encompassspa.com/products/phyto-a-brightening-treatment?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Retinol 0.3",
        "price": "$70",
        "href": "https://store.encompassspa.com/products/retinol-0-3?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Retinol 0.5",
        "price": "$80",
        "href": "https://store.encompassspa.com/products/retinol-0-5?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Retinol 1.0",
        "price": "$92",
        "href": "https://store.encompassspa.com/products/retinol-1-0?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Silymarin CF",
        "price": "$169",
        "href": "https://store.encompassspa.com/products/silymarin-cf?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Simply Clean",
        "price": "$36",
        "href": "https://store.encompassspa.com/products/simply-clean?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "SkinCeuticals LHA Cleanser",
        "price": "$45",
        "href": "https://store.encompassspa.com/products/skinceuticals-lha-cleanser?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "SkinCeuticals Purifying Cleanser",
        "price": "$39",
        "href": "https://store.encompassspa.com/products/skinceuticals-purifying-cleanser?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "TriPeptide-R Neck Repair",
        "price": "$126",
        "href": "https://store.encompassspa.com/products/tripeptide-r-neck-repair?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "Triple Lipid Restore",
        "price": "$136",
        "href": "https://store.encompassspa.com/products/triple-lipid-restore?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      },
      {
        "name": "youth eye complex",
        "price": "$110",
        "href": "https://store.encompassspa.com/products/youth-eye-complex?utm_source=website&utm_medium=skincare-page&utm_campaign=skinceuticals"
      }
    ]
  },
  {
    "heading": "Obagi",
    "items": [
      {
        "name": "CLENZIderm Daily Care Foam Cleanser",
        "price": "$44",
        "href": "https://store.encompassspa.com/products/clenziderm-daily-care-foam-cleanser?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "CLENZIderm M.D.® Pore Therapy",
        "price": "$44",
        "href": "https://store.encompassspa.com/products/clenziderm-m-d-®-pore-therapy?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "CLENZIderm Therapeutic Moisturizer",
        "price": "$44",
        "href": "https://store.encompassspa.com/products/clenziderm-therapeutic-moisturizer?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "ELASTIderm Eye Cream",
        "price": "$118",
        "href": "https://store.encompassspa.com/products/elastiderm-eye-cream?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "ELASTIderm Eye Serum",
        "price": "$118",
        "href": "https://store.encompassspa.com/products/elastiderm-eye-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "ELASTIderm Facial Serum",
        "price": "$198",
        "href": "https://store.encompassspa.com/products/elastiderm-facial-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "Hydrate",
        "price": "$55",
        "href": "https://store.encompassspa.com/products/hydrate?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "Nu-Derm® Trial Kit - Normal to Oily",
        "price": "$150",
        "href": "https://store.encompassspa.com/products/nu-derm®-trial-kit-normal-to-oily?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "Professional-C® Peptide Complex",
        "price": "$115",
        "href": "https://store.encompassspa.com/products/professional-c®-peptide-complex?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      },
      {
        "name": "Sun Shield Tint Broad Spectrum SPF 50",
        "price": "$54",
        "href": "https://store.encompassspa.com/products/sun-shield-tint-broad-spectrum-spf-50?utm_source=website&utm_medium=skincare-page&utm_campaign=obagi"
      }
    ]
  },
  {
    "heading": "SkinBetter Science",
    "items": [
      {
        "name": "AlphaRet Clearing Serum",
        "price": "$144",
        "href": "https://store.encompassspa.com/products/alpharet-clearing-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "AlphaRet Exfoliating Facial Peel Pads",
        "price": "$123",
        "href": "https://store.encompassspa.com/products/alpharet-exfoliating-facial-peel-pads?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "AlphaRet Overnight Cream",
        "price": "$144",
        "href": "https://store.encompassspa.com/products/alpharet-overnight-cream?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Alto Advanced Defense and Repair Serum",
        "price": "$200",
        "href": "https://store.encompassspa.com/products/alto-advanced-defense-and-repair-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Alto Defense Serum",
        "price": "$175",
        "href": "https://store.encompassspa.com/products/alto-defense-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Detoxifying Scrub Mask",
        "price": "$60",
        "href": "https://store.encompassspa.com/products/detoxifying-scrub-mask?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Even Tone Correcting Serum",
        "price": "$160",
        "href": "https://store.encompassspa.com/products/even-tone-correcting-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "InterFuse Intensive Treatment LINES",
        "price": "$145",
        "href": "https://store.encompassspa.com/products/interfuse-intensive-treatment-lines?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "InterFuse Treatment Cream EYE",
        "price": "$120",
        "href": "https://store.encompassspa.com/products/interfuse-treatment-cream-eye?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "InterFuse Treatment Cream FACE & NECK",
        "price": "$140",
        "href": "https://store.encompassspa.com/products/interfuse-treatment-cream-face-neck?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Mystro Active Balance Serum",
        "price": "$225",
        "href": "https://store.encompassspa.com/products/mystro-active-balance-serum?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Refining Foam Cleanser",
        "price": "$48",
        "href": "https://store.encompassspa.com/products/refining-foam-cleanser?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Solo Hydrating Defense Men",
        "price": "$170",
        "href": "https://store.encompassspa.com/products/solo-hydrating-defense-men?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "sunbetter TONE SMART SPF 68 Sunscreen Compact",
        "price": "$65",
        "href": "https://store.encompassspa.com/products/sunbetter-tone-smart-spf-68-sunscreen-compact?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "sunbetter TONE SMART SPF 75 Sunscreen Lotion",
        "price": "$75",
        "href": "https://store.encompassspa.com/products/sunbetter-tone-smart-spf-75-sunscreen-lotion?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      },
      {
        "name": "Trio Rebalancing Moisture",
        "price": "$155",
        "href": "https://store.encompassspa.com/products/trio-rebalancing-moisture?utm_source=website&utm_medium=skincare-page&utm_campaign=skinbetter-science"
      }
    ]
  },
  {
    "heading": "Hydrinity",
    "items": [
      {
        "name": "Hyacyn Active | Hydrinity",
        "price": "$60",
        "href": "https://store.encompassspa.com/products/hyacyn-active-hydrinity?utm_source=website&utm_medium=skincare-page&utm_campaign=hydrinity"
      }
    ]
  }
]
