#!/usr/bin/env node
/**
 * Regenerate lib/data/shop.ts from the live Shopify catalogue.
 *
 *   node scripts/sync-shop.mjs
 *
 * /collections/<handle>/products.json is PUBLIC on this store, so no API key
 * or app credential is needed to read titles, prices, stock and images.
 * Run it whenever the catalogue changes; prices on the site are a snapshot,
 * and the shelf says so.
 */
import { writeFileSync } from 'node:fs'

const SHOP = 'https://store.encompassspa.com'

const TITLES = {
  'adrenal-support': 'Adrenal Support',
  'blood-sugar-support': 'Blood Sugar Support',
  'cardiovascular-support': 'Cardiovascular Support',
  'energy-support': 'Energy Support',
  'gastrointestinal-health': 'Gastrointestinal Health',
  'general-nutrition': 'General Nutrition',
  'hormone-balance': 'Hormone Balance',
  'immune-support': 'Immune Support',
  'joint-and-muscle-health': 'Joint and Muscle Health',
  'liver-health-and-detoxification': 'Liver Health and Detoxification',
  memory: 'Memory & Mood Support',
  'sexual-health': 'Sexual Health',
  'skin-care': 'Skin Care',
  'weight-management': 'Weight Management',
}

async function collection(handle) {
  const items = []
  for (let page = 1; ; page++) {
    const r = await fetch(`${SHOP}/collections/${handle}/products.json?limit=250&page=${page}`)
    if (!r.ok) throw new Error(`${handle}: HTTP ${r.status}`)
    const { products = [] } = await r.json()
    if (!products.length) break
    items.push(
      ...products.map((p) => ({
        handle: p.handle,
        title: p.title,
        vendor: p.vendor,
        price: p.variants?.[0]?.price ?? null,
        available: (p.variants ?? []).some((v) => v.available),
        image: p.images?.[0]?.src ?? null,
      })),
    )
    if (products.length < 250) break
  }
  return items
}

const collections = {}
for (const handle of Object.keys(TITLES)) {
  const items = await collection(handle)
  collections[handle] = {
    handle,
    title: TITLES[handle],
    count: items.length,
    // Feature in-stock products that have an image, in catalogue order.
    products: items
      .filter((p) => p.available && p.image)
      .slice(0, 4)
      .map(({ handle, title, vendor, price, image }) => ({ handle, title, vendor, price, image })),
  }
  console.log(`${handle.padEnd(34)} ${String(items.length).padStart(3)} products`)
}

const out = `// Generated by scripts/sync-shop.mjs from the public Shopify catalogue at
// store.encompassspa.com (/collections/<handle>/products.json needs no API key).
// Do not edit by hand — re-run the script instead.
export const SHOP_URL = '${SHOP}'

export type ShopProduct = { handle: string; title: string; vendor: string; price: string | null; image: string | null }
export type ShopCollection = { handle: string; title: string; count: number; products: ShopProduct[] }

export const COLLECTIONS: Record<string, ShopCollection> = ${JSON.stringify(collections, null, 2)}

export function collectionUrl(handle: string) { return \`\${SHOP_URL}/collections/\${handle}\` }
export function productUrl(handle: string) { return \`\${SHOP_URL}/products/\${handle}\` }
`
writeFileSync('lib/data/shop.ts', out)
console.log('\nwrote lib/data/shop.ts')
